const List<Map<String, dynamic>>  products=[
  { 'title': 'Addidas',
    'name': 'Adidas Men\'s Zap-Run 2 Running Shoes',
    'price': 1000,
    'image': 'assets/images/add1.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },
  {
    'title': 'Addidas',
    'name': 'Adidas Mens Duramo Sl 2.0 Running ShoesRunning Shoe',
    'price': 1100,
    'image': 'assets/images/add2.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },
  {
    'title': 'Addidas',
    'name': 'Adidas Samba OG White',
    'price': 1800,
    'image': 'assets/images/add3.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  }, {
    'title': 'Addidas',
    'name': 'Adidas sneakers',
    'price': 1300,
    'image': 'assets/images/add4.png',
    'size': ['5', '6', '7', '8', '9', '10'],
  },
  
   {
    'title': 'Addidas',
    'name': 'Men Zapid Running Shoes',
    'price': 1100,
    'image': 'assets/images/add5.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },
  {
    'title': 'Bata',
    'name': 'Bata Black Loafers For Men',
    'price': 2000,
    'image': 'assets/images/bata1.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },
  {
    'title': 'Bata',
    'name': 'Bata comfit Men Textured Round Toe Sneakers with Lace Up Closure',
    'price': 4000,
    'image': 'assets/images/bata2.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },
  {
    'title': 'Bata',
    'name': 'Bata Corporate Casuals for Men',
    'price': 3200,
    'image': 'assets/images/bata3.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },  
    {
    'title': 'Bata',
    'name': 'Bata Men Bata Casual Lace-Up Sneakers',
    'price': 2200,
    'image': 'assets/images/bata4.png',
    'size': [ '7', '8', '9', '10', '11', '12'],
  }, 
  {
    'title': 'Sparx',
    'name': 'Sparx Athleisure Shoes',
    'price': 1500,
    'image': 'assets/images/sparx1.png',
    'size': ['5', '6', '7', '8', '9', '10'],
  },
  {
    'title': 'Sparx',
    'name': 'SPARX Men Lace Up Sneaker Shoes',
    'price': 800,
    'image': 'assets/images/sparx2.png',
    'size': ['5', '6', '7', '8', '9', '10', '11'],
  },
  {
    'title': 'Sparx',
    'name': 'Sparx Men\'s Running Shoes',
    'price': 1000,
    'image': 'assets/images/sparx3.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },
  {
    'title': 'Sparx',
    'name': 'SPARX Mens Sm 648 Running Shoe',
    'price':900,
    'image': 'assets/images/sparx4.png',
    'size': ['5', '6', '7', '8', '9', '10'],
  },
  {
    'title': 'Nike',
    'name': 'Air Jordan 1 High Fragment Design',
    'price': 123200,
    'image': 'assets/images/nike1.png',
    'size': ['5', '6', '7', '8', '9', '10'],
  },
  {
    'title': 'Nike',
    'name': 'Nike Court Vision Low Men\'s Shoes',
    'price': 2000,
    'image': 'assets/images/nike2.png',
    'size': ['5', '6', '7', '8', '9', '10'],
  },
  {
    'title': 'Nike',
    'name': 'Nike Legend Essential 3 Next Nature Men',
    'price': 4500,
    'image': 'assets/images/nike3.png',
    'size': ['5', '6', '7', '8', '9', '10'],
  },
  {
    'title': 'Nike',
    'name': 'Nike Promina Men\'s Walking Shoes',
    'price': 3200,
    'image': 'assets/images/nike4.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },
  {
    'title': 'Puma',
    'name': 'Puma Men\'s RS-X2.0 Sneakers',
    'price': 1200,
    'image': 'assets/images/puma1.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },
  {
    'title': 'Puma',
    'name': 'Puma Men\'s FusionPro Lightweight Cushioned Running Shoes',
    'price': 1800,
    'image': 'assets/images/puma2.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },  {
    'title': 'Puma',
    'name': 'Puma Unisex Adult Smashic Sneaker',
    'price': 1800,
    'image': 'assets/images/puma3.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },  {
    'title': 'Puma',
    'name': 'Puma X-Ray 2 Square Sneakers',
    'price': 2500,
    'image': 'assets/images/puma4.png',
    'size': ['5', '6', '7', '8', '9', '10', '11', '12'],
  },
];